# Generated by Django 3.1.1 on 2020-11-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201105_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['create']},
        ),
    ]
