# Generated by Django 3.1.4 on 2021-01-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201106_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modelname',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
