# Generated by Django 3.1.4 on 2021-01-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_modelname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'ordering': ['create']},
        ),
    ]
