# Generated by Django 3.1.4 on 2021-01-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210124_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['create']},
        ),
    ]
