# Generated by Django 3.1.1 on 2020-10-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create'], 'verbose_name': '文章编辑', 'verbose_name_plural': '文章编辑'},
        ),
    ]
