# Generated by Django 3.1.4 on 2021-01-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='modelname',
            field=models.CharField(default='case', max_length=50),
        ),
    ]
