"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from .base import *
import os
from pathlib import Path

SECRET_KEY = os.environ['SECRET_KEY']
# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = False
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['*']
DATABASE_PASSWORD =os.environ['DATABASE_PASSWORD']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite',
        'USER': 'root',
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



