# Generated by Django 3.1.1 on 2020-12-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_password', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
